name: "_mobileclip_s0_text_pipeline"
backend: "python"
parameters {
  key: "steps"
  value: {
    string_value: "_mobileclip_s0_text_preprocessing:tokens,_mobileclip_s0_text_backend:embeddings"
  }
}
max_batch_size: 64
input [
  {
    name: "text"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "embeddings"
    data_type: TYPE_FP32
    dims: [ 512 ]
  }
]
instance_group [
  {
    kind: KIND_CPU
    count: 4
  }
]
